CREATE TABLE SPECIALCAKES (
 CAKETYPE             CHAR(12),
 MULTITIER            CHAR(3),
 BASICCOST            DECIMAL(4,2),
 PKEY				  SMALLINT(2) NOT NULL,
PRIMARY KEY (PKEY));


INSERT INTO SPECIALCAKES VALUES ('CHOCOLATE','YES',12.50,1);
INSERT INTO SPECIALCAKES VALUES ('FRUIT','YES',20.00,2);
INSERT INTO SPECIALCAKES VALUES ('LEMON','YES',12.50,3);
INSERT INTO SPECIALCAKES VALUES ('CARROT','NO',10.00,4);
INSERT INTO SPECIALCAKES VALUES ('STRAWBERRY','NO',12.50,5);
